print("-"*75)
print("\t\t\t Report Card")
print("-"*75)
print("Name",  "\t\t:","\t Sirname","\t:")
print("Class","\t\t:","\t Section","\t:")
print("Telephone no.","\t:","\t MB. NO","\t:")
print("-"*75)
